### ISSUE TITLE
Recurring payments not triggering Civi Records 

### ISSUE THREAD

**Issue by kevindees** [iATSPayments/com.iatspayments.civicrm#206]
Hey everyone,

We are working with our client to fix some issues with recurring payments and updating memberships when the payment is processed. We are having a hard time tracking down the cause for them.

There is good news, all the gifts were processed properly by iATS. The bad news is that things were not recorded properly in Civi.

**Here is our setup**:

Recently updated from Civi 4.6 to 4.7 along with the iATS plugin.

- Apache 2.4
- PHP 5.5
- MySQL 5.5
- Civi 4.7
- iATS plugin 1.6

**Here is what we found**:
 
1. There were 575 active recurring gifts scheduled to run on the 1st of each month. The iATS scheduled job log in Civi records that all were processed, with a result either of approved or declined.
2. Our iATS Journal records that all 575 gifts were attempted. 557 were approved, and 18 were declined. So far this all is as it should be.
3. **Here starts the problem**, The first 23 recurring gifts were not recorded in Civi (No contribution record, no activity record, next transaction date not updated to July 1st, membership not renewed).
4. Another 12 gifts were recorded properly, but their associated memberships were not renewed.
5. On a more positive note, the handful of memberships that previously were not renewing (due to my having changed the amount on the recurring gift) appear to be renewing properly again.
 
We have been able to import the missing contributions, renewed all the memberships as needed, and updated next transaction dates.

Any help would be welcome.

Thanks,
Kevin

**Comment by adixon** [comment]
Fascinating ... sounds like an issue of how the code is handling server-type failures.

As an aside - the next version of the plugin (currently in testing) will be able to handle more errors, but pulling data from iATS even if it doesn't get it on the first try.

My best read from what you've provided here is that the first 23 transacted and then that data somehow got lost to CiviCRM (maybe some kind of sql failure and then rollback? Or an automated-backup that collided?).

Separately: if the gifts are recorded properly but the membership isn't renewed, then that sounds like a separate issue with how the memberships are configured and/or Civi core code - the iATS plugin won't be involved in that bit (assuming you updated to a recent 4.7).

Are you able to check the civicrm log? I've been using my https://github.com/adixon/ca.civicrm.logviewer recently to make checking it very handy.

**Comment by kevindees** [comment]
Here are some of the log errors I am getting:

```
Aug 01 00:45:02  [info] $Fatal Error Details = Array
(
    [message] => Could not connect to MailStore for civicrm@example.com@localhost&lt;p&gt;Error message: &lt;pre&gt;An error occured while sending or receiving mail. Failed to connect to the server: localhost:143.&lt;/pre&gt;&lt;p&gt;
    [code] => 
)


Aug 01 00:45:02  [info] $backTrace = #0 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php(336): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Mail/EmailProcessor.php(173): CRM_Core_Error::fatal("Could not connect to MailStore for civicrm@example.com@localhost<p>Erro...")
#2 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Mail/EmailProcessor.php(57): CRM_Utils_Mail_EmailProcessor::_process(TRUE, Object(CRM_Core_DAO_MailSettings), 0)
#3 /var/www/html/wp-content/plugins/civicrm/civicrm/api/v3/Job.php(361): CRM_Utils_Mail_EmailProcessor::processBounces(0)
#4 /var/www/html/wp-content/plugins/civicrm/civicrm/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_job_fetch_bounces((Array:2))
#5 /var/www/html/wp-content/plugins/civicrm/civicrm/Civi/API/Kernel.php(169): Civi\API\Provider\MagicFunctionProvider->invoke((Array:9))
#6 /var/www/html/wp-content/plugins/civicrm/civicrm/Civi/API/Kernel.php(100): Civi\API\Kernel->runRequest((Array:7))
#7 /var/www/html/wp-content/plugins/civicrm/civicrm/api/api.php(23): Civi\API\Kernel->runSafe("job", "fetch_bounces", (Array:1), NULL)
#8 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/JobManager.php(134): civicrm_api("job", "fetch_bounces", (Array:1))
#9 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/JobManager.php(79): CRM_Core_JobManager->executeJob(Object(CRM_Core_ScheduledJob))
#10 /var/www/html/wp-content/plugins/civicrm/civicrm/api/v3/Job.php(99): CRM_Core_JobManager->execute(FALSE)
#11 /var/www/html/wp-content/plugins/civicrm/civicrm/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_job_execute((Array:2))
#12 /var/www/html/wp-content/plugins/civicrm/civicrm/Civi/API/Kernel.php(169): Civi\API\Provider\MagicFunctionProvider->invoke((Array:9))
#13 /var/www/html/wp-content/plugins/civicrm/civicrm/Civi/API/Kernel.php(100): Civi\API\Kernel->runRequest((Array:7))
#14 /var/www/html/wp-content/plugins/civicrm/civicrm/api/api.php(23): Civi\API\Kernel->runSafe("Job", "execute", (Array:2), NULL)
#15 /var/www/html/wp-content/plugins/civicrm/civicrm/bin/cli.class.php(112): civicrm_api("Job", "execute", (Array:2))
#16 /var/www/html/wp-content/plugins/civicrm/civicrm/bin/cli.php(32): civicrm_cli->callApi()
#17 {main}


Aug 01 01:45:02  [warning] Deprecated function, use CRM_Core_PseudoConstant::getKey
Array
(
    [civi.tag] => deprecated
)


Aug 01 01:45:02  [info] $Fatal Error Details = Array
(
    [message] => Could not connect to MailStore for civicrm@example.com@localhost&lt;p&gt;Error message: &lt;pre&gt;An error occured while sending or receiving mail. Failed to connect to the server: localhost:143.&lt;/pre&gt;&lt;p&gt;
    [code] => 
)
```

and

```
Aug 01 03:00:04  [info] $Fatal Error Details = Array
(
    [callback] => Array
        (
            [0] => CRM_Core_Error
            [1] => exceptionHandler
        )

    [code] => -1
    [message] => DB Error: unknown error
    [mode] => 16
    [debug_info] => 
        DELETE gc
        FROM civicrm_group_contact_cache gc
        INNER JOIN civicrm_group g ON g.id = gc.group_id
        WHERE g.cache_date <= '20170801025504'
       [nativecode=1213 ** Deadlock found when trying to get lock; try restarting transaction]
    [type] => DB_Error
    [user_info] => 
        DELETE gc
        FROM civicrm_group_contact_cache gc
        INNER JOIN civicrm_group g ON g.id = gc.group_id
        WHERE g.cache_date <= '20170801025504'
       [nativecode=1213 ** Deadlock found when trying to get lock; try restarting transaction]
    [to_string] => [db_error: message="DB Error: unknown error" code=-1 mode=callback callback=CRM_Core_Error::exceptionHandler prefix="" info="
        DELETE gc
        FROM civicrm_group_contact_cache gc
        INNER JOIN civicrm_group g ON g.id = gc.group_id
        WHERE g.cache_date <= '20170801025504'
       [nativecode=1213 ** Deadlock found when trying to get lock; try restarting transaction]"]
)
```

```
Aug 03 02:18:10  [info] $Fatal Error Details = Array
(
    [message] => The requested Profile (gid=15) is disabled OR it is not configured to be used for 'Profile' listings in its Settings OR there is no Profile with that ID OR you do not have permission to access this profile. Please contact the site administrator if you need assistance.
    [code] => 
)

Aug 03 08:40:14  [warning] Deprecated function, use CRM_Core_PseudoConstant::getKey
Array
(
    [civi.tag] => deprecated
)
```

**Comment by adixon** [comment]
First, fix your mail settings to get rid of those 'failed to connect' messages, they are just noise for this issue.

The deadlock issue is a symptom of several potential issues unfortunately, but my first guess is that you've got quite a big database and/or too many smart groups.
