### ISSUE TITLE
Error message when donors attempt a contribution

### ISSUE THREAD

**Issue by IowaBoy1** [iATSPayments/com.iatspayments.civicrm#256]
CiviCRM 5.3.1
iATSPayments 1.6.1
Drupal 7.59

Earlier this year I switched from WordPress to Drupal. I do not think I have Allan's Logging extension installed after the switch. That probably is needed for this. Where do I find it and where do I put it in my file structure?

I have donors reporting that they are getting an error message when they attempt to make a contribution. The message is that the website encountered an error. I do not see any record of the attempted contribution on my side.
Thanks

**Comment by KarinG** [comment]
Hi - 

This is Alan's logviewer extension https://civicrm.org/extensions/civicrm-log-viewer - it's not CMS specific - but indeed super handy.

Set up an iATS TEST88 payment processor [live: TEST88/TEST88]-> then clone your form -> enable the TEST88 payment processor on that form -> then try make a donation - to reproduce this. As soon as you hit an error message -> check that logviewer -to see what the actual error is in the configandlog file. That should provide some clues as to what's going on. 

One quick thought: iATS recently upgraded their TLS requirements.

**Comment by IowaBoy1** [comment]
I did think of the TLS requirement. But they attempted a donation that failed. They did one that processed, and now they tried the third time and it failed again. All on the same machine. But I can have them check their TLS settings to be sure.

I just thought about it that I have the Drupal error logging that I could look at. It is showing this error for that contribution page. Notice: Undefined index: location_type_id in CRM_Dedupe_BAO_Rule->sql() (line 96 of /home/radius/www/secure/sites/all/modules/civicrm/CRM/Dedupe/BAO/Rule.php). Does this point to anything that be related?

**Comment by KarinG** [comment]
That's just a notice - we're looking for a Fatal error. 

Try reproduce it with TEST88 and - or if they tried just now and it failed - check your ConfigAndLog file (either by viewing it from a shell or by using Alan's logviewer extension). Let me know what you find out.

**Comment by IowaBoy1** [comment]
I am struggling to figure out how to view the errors. I cannot find instructions related to using the extension. Sorry

**Comment by KarinG** [comment]
np - Did you get it installed? Then it's CiviCRM -> Administer -> Administration Console -> View Log

**Comment by KarinG** [comment]
I need to step out for a bit - but will check back in later.

**Comment by IowaBoy1** [comment]
**I tried it twice using the Test88 and I got the following error in the log**

50799 | Aug 23 19:56:20 | [error] Configured geocoder is invalid, must provide a format method
-- | -- | --
50792 | Aug 23 19:53:29 | [error] Configured geocoder is invalid, must provide a format method

**Then I tried it for real and it processed without any errors.**

I am seeing the following set of errors regularly in my log (I did have the logging set up previously, I just forgot and did not know where to view the logs)

49102 | Aug 22 19:42:14 | [warning] addCurrency: Currency is disabled but still in use!
-- | -- | --
49082 | Aug 22 16:45:28 | [info] $backTrace = #0 /home/radius/www/secure/sites/all/modules/civicrm/CRM/Core/Error.php(381): CRM_Core_Error::backtrace("backTrace", TRUE)
49075 | Aug 22 16:45:28 | [info] $Fatal Error Details = Array


**Here is the details for #49075 $Fatal Error Details = Array**

Log Entry for Aug 22 16:45:28
 [info] $Fatal Error Details = Array
(
    [message] => processor_id (value: ) is not of the type Integer
    [code] => 
)

**Comment by KarinG** [comment]
Did you have one configured in the past?

**Comment by IowaBoy1** [comment]
Yes. I think Google. I dropped it when I swtiched to Drupal. I was getting an error message so I went with nothing

**Comment by KarinG** [comment]
When googling that Error you're getting I can across issues describing problems when disabling a Geocoder. 

I suspect the Error wasn't related to switching to Drupal - but to changes in Google - a few months back Google changed how they handle API keys for mapping. You now need to provide a credit card to get an API key. It comes with a $200/mo credit and that's plenty for most - but it means get new key.

**Comment by IowaBoy1** [comment]
I now have the Google Geocode API in place and I am no longer getting the Geocode error.

Karin said, "[message] => processor_id (value: ) is not of the type Integer - that's concerning - but difficult to understand without the context (what page / button did someone hit when that happened)." I had 3 Fatal Error Arrays happen on 8/23 (2 days ago) that were recurring contributions that have been successfully processing until this month. 

These failed recurring transactions were a combination of ACH and CC. The one donor has 2 active recurring contributions running. The other one processed successfully this morning.  

I have successfully made 4 live contributions this morning. Two of them the Geocode API failed because I did not have it configured correctly. The last two did not get the Geocode error.

**Comment by IowaBoy1** [comment]
Actually upon further review, I do not think that the 3 recurring contributions failure is the same as my original problem. In the log, the results look the same. But when I clicked on the details for the Fatal Error, I got a different message than I reported above. 
[info] $Fatal Error Details = Array
(
    [message] => There is a validation error with your HTML input. Your activity is a bit suspicious, hence aborting
    [code] => 
)


There is a bunch of IDS messages before and after these 3 failed. 

Aug 23 10:26:51 | [info] $IDS Detector Details = Array
-- | --

So, I think the 3 recurring failures are unrelated to issue reported in this thread.

**Comment by IowaBoy1** [comment]
I am going back through the 33 Fatal Errors. I am now seeing that not all of the Fatal Error Details are the same in the details. Over half are the following.
[info] $Fatal Error Details = Array
(
    [message] => We can't load the requested web page. This page requires cookies to be enabled in your browser settings. Please check this setting and enable cookies (if they are not enabled). Then try again. If this error persists, contact the site administrator for assistance.

Site Administrators: This error may indicate that users are accessing this page using a domain or URL other than the configured Base URL. EXAMPLE: Base URL is http://example.org, but some users are accessing the page via http://www.example.org or a domain alias like http://myotherexample.org.

Error type: Could not find a valid session key.
    [code] => 
)

The rest are the previous  [message] => processor_id (value: ) is not of the type Integer

I do have alias urls setup for my contribution pages so I can send donors to /give-financially/ instead of the CiviCRM ugly url. I just did a live contribution using an alias url and it processed successfully.

**Comment by IowaBoy1** [comment]
Aug 25 20:20:10 | [info] $backTrace = #0 /home/radius/www/secure/sites/all/modules/civicrm/CRM/Core/Error.php(381): CRM_Core_Error::backtrace("backTrace", TRUE)
-- | --
51060 | Aug 25 20:20:10 | [info] $Fatal Error Details = Array

BackTrace Details
 [info] $backTrace = #0 /home/radius/www/secure/sites/all/modules/civicrm/CRM/Core/Error.php(381): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /home/radius/www/secure/sites/all/modules/civicrm/CRM/Core/Controller.php(833): CRM_Core_Error::fatal("We can't load the requested web page. This page requires cookies to be enable...")
#2 /home/radius/www/secure/sites/all/modules/civicrm/CRM/Core/Controller.php(853): CRM_Core_Controller->invalidKeyCommon()
#3 /home/radius/www/secure/sites/all/modules/civicrm/CRM/Contribute/Form/ContributionBase.php(228): CRM_Core_Controller->invalidKeyRedirect()
#4 /home/radius/www/secure/sites/all/modules/civicrm/CRM/Contribute/Form/Contribution/Main.php(63): CRM_Contribute_Form_ContributionBase->preProcess()
#5 /home/radius/www/secure/sites/all/modules/civicrm/CRM/Core/Form.php(562): CRM_Contribute_Form_Contribution_Main->preProcess()
#6 /home/radius/www/secure/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Display.php(92): CRM_Core_Form->buildForm()
#7 /home/radius/www/secure/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Display->perform(Object(CRM_Contribute_Form_Contribution_Main), "display")
#8 /home/radius/www/secure/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Contribute_Form_Contribution_Main), "display")
#9 /home/radius/www/secure/sites/all/modules/civicrm/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle("display")
#10 /home/radius/www/secure/sites/all/modules/civicrm/CRM/Core/Invoke.php(309): CRM_Core_Controller->run((Array:3), NULL)
#11 /home/radius/www/secure/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:15))
#12 /home/radius/www/secure/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#13 /home/radius/www/secure/sites/all/modules/civicrm/drupal/civicrm.module(445): CRM_Core_Invoke::invoke((Array:3))
#14 [internal function](): civicrm_invoke("contribute", "transact")
#15 /home/radius/www/secure/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
#16 /home/radius/www/secure/index.php(21): menu_execute_active_handler()
#17 {main}

Fatal Error Details
[info] $Fatal Error Details = Array
(
    [message] => We can't load the requested web page. This page requires cookies to be enabled in your browser settings. Please check this setting and enable cookies (if they are not enabled). Then try again. If this error persists, contact the site administrator for assistance.

Site Administrators: This error may indicate that users are accessing this page using a domain or URL other than the configured Base URL. EXAMPLE: Base URL is http://example.org, but some users are accessing the page via http://www.example.org or a domain alias like http://myotherexample.org.

Error type: Could not find a valid session key.
    [code] => 
)

**Comment by adixon** [comment]
So these are triggered by a page load, not a recurring payment cron, so this is not the key issue for this post right? 

My guess (as above) is that these are triggered by badly behaving bots that are spidering your contribution pages, but if that's not the case, then you probably want to investigate the suggested causes (e.g. the multiple domain issue). In short - the error comes because civicrm can't connect the page request to a session on it's system, which could have a variety of causes, and it's a fatal error.

**Comment by adixon** [comment]
Closing due to lack of activity.
